name: Check docker build

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'main.py'
      - 'requirements.txt'
  pull_request:
    branches:
      - dev
      - main
    paths:
      - 'main.py'
      - 'requirements.txt'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tommythebeast/arrstalledhandler:$(date +%s)
