name: Delete Docker image on Release Delete

on:
  release:
    types: [deleted]

jobs:
  delete_from_registry:
    name: Delete Docker image from Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      REGISTRY: docker.io
      IMAGE_NAME: tommythebeast/arrstalledhandler
    steps:
      - name: Log in to Docker Hub
        run: |
          echo "Logging into Docker Hub..."
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Delete Docker image
        run: |
          IMAGE_TAG="${{ github.event.release.tag_name }}"
          REPO="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          echo "Attempting to delete image: $REPO:$IMAGE_TAG"

          # Retrieve the digest for the given tag
          DIGEST=$(curl -s -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" \
            "https://hub.docker.com/v2/repositories/$REPO/tags/$IMAGE_TAG" | jq -r '.images[0].digest')

          if [ "$DIGEST" != "null" ]; then
            echo "Found digest: $DIGEST. Deleting..."
            curl -s -X DELETE -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" \
              "https://hub.docker.com/v2/repositories/$REPO/manifests/$DIGEST"
            echo "Docker image deleted successfully."
          else
            echo "Tag not found or already deleted: $IMAGE_TAG"
          fi

      - name: Logout from Docker Hub
        run: |
          docker logout
