name: Update Docker Hub Description

on:
  push:
    branches:
      - main  # Adjust if your default branch is not "main"
    paths:
      - README.md  # Trigger only when README.md is updated

jobs:
  update-dockerhub-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ vars.DOCKER_IMAGE }}
          readme-filepath: ./README.md  # Ensure README.md is in the root of your repository
          enable-url-completion: true  # Optional: Completes relative URLs to absolute ones
